- laplace/baselaplace.py
- laplace/lllaplace.py
- tests/test_baselaplace.py
- tests/test_lllaplace.py
- tests/test_matrix.py
- tests/test_utils.py
- tests/utils.py
Changes:
- make `mean` a quantity that falls back to prior when not yet fit and is set on `.fit()` so that `.log_prob()` is correct
- add `log_prob(value)` to compute log density under LA for regularization. This falls back to prior before fitting the LA
- add `.fit(train_loader, override=True)` where `override` means to reset Hessian approximation while `override == False` leads to adding up curvature, e.g., for continual learning
> Support for refitting LA with option to override or update

- laplace/baselaplace.py
- laplace/curvature/__init__.py
- laplace/curvature/asdl.py
- laplace/lllaplace.py
- tests/test_baselaplace.py
- tests/test_lllaplace.py
This is an alternative to #71: it addresses a bug resulting from #62, first reported [here](https://github.com/runame/laplace-experiments/pull/17) (note: links to PR discussion in private repository). For the last-layer LA flavors the Hessian approximation `H` was first initialized for all-weights, which leads to out-of-memory errors for larger models.
The advantage of the previous fix is that it keeps the classes for all-weights and last-layer flavors more strictly separated, which might make it harder to introduce similar bugs in the future. However, many more classes are necessary. @AlexImmer and me agreed that this additional complexity is probably not worth it.
Changes:
- Add better tests for the initialization of all the Laplace classes, also with a large model (Wide ResNet 50-2), …
> Keep initialization of H for all-weights and last-layer separate

- laplace/__init__.py
- laplace/curvature/asdl.py
- laplace/curvature/backpack.py
- laplace/laplace.py
- laplace/subnetlaplace.py
- tests/test_subnetlaplace.py
This PR aims to address #86. Namely, this implements the following changes:
- It fixes an issue where the subnet indices validity check would fail on GPU as we only allowed `torch.LongTensors` but not `torch.cuda.LongTensors`.
- It technically enables marginal likelihood computation and therefore optimization with `SubnetLaplace` (i.e. essentially makes sure that there are no dimension errors when calling `la.log_marginal_likelihood()` on a `SubnetLaplace` model); however we should generally not recommend using this, as the marginal likelihood is probably not meaningful when computed over a subnetwork (without any additional care that would likely require original research); so I'm not sure whether we should have this feature if we don't know how it'll behave.
- It adds …
> Fixes and features for SubnetLaplace

- laplace/baselaplace.py
- laplace/utils/__init__.py
- laplace/utils/utils.py
- tests/test_utils.py
Addresses #93 and #91 with following changes:
- add function to sample normal using broadcasting (#91) which leads to smoother predictives
- allow controlling randomness by passing `torch.Generator` (#91)
- diagonalize posterior predictive on output level only when asked for explicitly (#93)
> Improve predictive samples

- laplace/baselaplace.py
- laplace/utils/utils.py
- tests/test_baselaplace.py
- tests/test_lllaplace.py
- tests/test_subnetlaplace.py
Adjust LA bridge predictive to latest version of the paper. Thanks to @mariushobbhahn for the code blueprint.
I have also added a check to make sure people don't think they are using any other link approximation than `'mc'` together with `pred_type='nn'`.
> Update Laplace bridge predictive

- laplace/curvature/curvature.py
Defines `output_size` such that it is agnostic to the specific shape of the neural network output `f`.
> Make last-layer Jacobians agnostic to NN output shape

- laplace/utils/utils.py
Before this fix calling `to_matrix()` on an instance of the `Kron` class did not preserve the dtype and device, so even when everything is computed on GPU the returned matrix used to be on CPU, which is unexpected behavior.
> Fix device and dtype of `block_diag` used for `Kron.to_matrix()`

- .gitignore
- examples/bayesopt_example.py
- examples/regression_example.py
- examples/requirements.txt
- laplace/baselaplace.py
- laplace/curvature/asdl.py
- laplace/curvature/backpack.py
- laplace/curvature/curvature.py
- laplace/lllaplace.py
- laplace/marglik_training.py
- laplace/utils/feature_extractor.py
- setup.cfg
- tests/test_baselaplace.py
- tests/test_curv_backends_backpack.py
- tests/test_jacobians.py
- tests/test_lllaplace.py
Changes:
* Remove `detach()` in GLM predictive so that one can backprop from `f(x)` to `x`, in particular for optimizing acquisition functions.
* Add `functional_covariance` method for GLM predictive that returns the `(nk,)` mean and the `(nk, nk)` covariance over `n` input points and `k` outputs.
* Add example implementation of a linearized-Laplace-based BoTorch model for BayesOpt.
> Enable BayesOpt

- laplace/curvature/asdl.py
The `kfac_conv` argument breaks the usage of this branch with the current ASDL main branch.
> Remove `kfac_conv` argument for compatibility with current ASDL main branch

- laplace/curvature/asdl.py
- laplace/curvature/backpack.py
Needed for, e.g., language data with multiple leading dimensions `(batch_size, n_tokens, ...)`. We assume that the last dimension of the model outputs is of size `n_outputs` (consistent with ASDL); hence, we can flatten all other dimensions into the batch dimension.
> Add support for cross entropy loss inputs with multiple leading dimensions

- laplace/baselaplace.py
- laplace/curvature/asdl.py
- laplace/lllaplace.py
- laplace/subnetlaplace.py
Add `asdl_fisher_kwargs` argument to be able to specify ASDL's `FisherConfig` values like `kfac_linear`, `diag_A/B`, and `autocast`.
@AlexImmer Can you check that my changes in line 848 and 852 of `baselaplace.py` don't break anything? Not sure why this was differently implemented here than in other places.
~Also, I have noticed that the tests are broken, which is really weird since I'm almost certain that I ran them successfully for my last PR. I went back to [this commit](https://github.com/AlexImmer/Laplace/commit/99278beb81d613bccac934b11158e7066ec8d34d) and they are already broken at this point. We will have to look into this.~
~_Edit:_ Ok, just checked and this PR seems to break a few more tests than the ones that were broken already, so maybe do not merge yet, will fix this …
> Add `asdl_fisher_kwargs` argument

- laplace/baselaplace.py
- laplace/utils/__init__.py
- laplace/utils/metrics.py
- laplace/utils/utils.py
- setup.cfg
- tests/test_metrics.py
- tests/test_utils.py
Support running metrics in cross validation of prior precision. Rationale: gathering data then computing metric is very expensive if `n_data` is very large.  
There are some failed tests for LLLaplace, but I think they are unrelated.
> Running metrics

- laplace/utils/matrix.py
- tests/test_baselaplace.py
- tests/test_lllaplace.py
- tests/test_matrix.py
- tests/utils.py
To support diagonal Kronecker factors in this library we have to adopt the methods of the `Kron` matrix class to be able to handle this correctly.
> Add support for diagonal Kronecker factors in `Kron` matrix class

- README.md
- laplace/baselaplace.py
- laplace/marglik_training.py
- laplace/utils/__init__.py
- laplace/utils/utils.py
Changes:
- Add a helper function `fix_prior_prec_structure` for marglik optimization.
- Add `prior_structure` argument to `optimize_prior_precision`, such that we can easily optimize a layer-wise or diagonal prior precision post-hoc.
- Rename the method `CV` for `optimize_prior_precision` to `gridsearch`.
> Add `prior_structure` argument to `optimize_prior_precision`

- README.md
- laplace/baselaplace.py
- laplace/curvature/__init__.py
- laplace/curvature/asdl.py
- laplace/curvature/backpack.py
- laplace/curvature/curvature.py
- laplace/curvature/curvlinops.py
- laplace/lllaplace.py
- laplace/subnetlaplace.py
- laplace/utils/matrix.py
- setup.cfg
- tests/test_curv_backend.py
- tests/test_curv_backends_backpack.py
- tests/test_curv_backends_curvlinops.py
- tests/test_curv_backends_interface.py
- tests/test_jacobians.py
- tests/test_lllaplace.py
- tests/test_subnetlaplace.py
Changelog:
1. Add [Curvlinops](https://github.com/f-dangel/curvlinops/tree/main) backend.
2. Add default `functorch` implementation for many quantities: (in `CurvatureInterface` itself)
1. Jacobians 
2. Batch gradients
3. Diag GGN (both stochastic and exact) and diag EF
4. Full GGN (both stochastic and exact) and full EF
**Rationale for (1):** BackPACK & ASDL are not actively supported anymore and are hard to extend. Note that we use Curvlinops mainly for KFACs. 
**Rationale for (2):** `functorch` is a first-class PyTorch module => has the highest compatibility to any PyTorch models => futureproofing `laplace-torch`, less dependence to third-party backends
**Together:** They make `laplace-torch` very flexible and compatible with most architectures out there (and in the future).
With this …
> Add Curvlinops backend & add default `functorch` implementations of many curvature quantities

- setup.cfg
Useful when people do
```
pip install git+https://git@github.com/aleximmer/laplace
```
or 
```
git clone pip install https://github.com/aleximmer/laplace
cd laplace
pip install -e .
```
Addressing #150
> Point to curvlinops master branch in setup.cfg

- .gitignore
- README.md
- examples/regression_example.py
- laplace/baselaplace.py
- laplace/lllaplace.py
- laplace/utils/matrix.py
- tests/test_serialization.py
Addressing #45. Very useful for large models like LLMs where even doing forward passes over training data (for `fit()`) is expensive.
The API basically follows PyTorch.
```python
la = Laplace(model, 'regression', subset_of_weights='all', hessian_structure='full')
la.fit(train_loader)
la.optimize_prior_precision()  # Or via marglik optimizing sigma_noise also
state_dict = la.state_dict()
torch.save(state_dict, 'state_dict.bin')
la2 = Laplace(model, 'regression', subset_of_weights='all', hessian_structure='full')
la2.load_state_dict(torch.load('state_dict.bin'))
```
> Add native serialization support

- examples/calibration_example.py
- examples/helper/dataloaders.py
- laplace/lllaplace.py
- laplace/utils/feature_extractor.py
- tests/test_lllaplace.py
Closes #161. 
@runame as discussed in the other PR. Please wait until #144  is merged, though.
> Feature caching mechanism in LLLA

- laplace/curvature/curvlinops.py
- makefile
- setup.cfg
The `loss_average` argument of `KFACLinearOperator` in `curvlinops` was just removed [here](https://github.com/f-dangel/curvlinops/pull/117). Hence, I removed the single use of this argument in this repo.
Also, I added a makefile to bundle both ruff commands into one (`make ruff`) since this is a very common workflow.
> Remove depreciated `loss_average` argument of `KFACLinearOperator` and add makefile for ruff

- README.md
Closes #196 
@runame please double check.
> Add "Contributing" to the README

- laplace/baselaplace.py
- laplace/utils/utils.py
- tests/test_baselaplace.py
Suggested refactor of the reward-modeling likelihood, let me know if I missed something. Advantages:
1. Simplicity and readability. We get rid of `self.reward_modeling` and `self._fitting` (actually `self._fitting` was not even used before, not sure if you had a future use case in mind?).
2. When a user calls `la.likelihood` it will always return `"reward_modeling"` which should be the expected behavior.
(Unrelated: I also removed a superfluous `loss_with_var` argument.)
> Refactor reward-modeling likelihood

- README.md
- examples/huggingface_example.md
- laplace/baselaplace.py
Closes #103.
Add some checks in `optimize_prior_precision`, and notify users in README.
@runame please review. Feel free to suggest further checks.
> Add some checks in `optimize_prior_precision`

- setup.cfg
According to [PEP 561], packages with inline type annotations should put a `py.typed` marker file in their package directory. This fixes mypy [`import-untyped`] errors when type checking code which imports `laplace`:
```
error: Skipping analyzing "laplace": module is installed, but missing library stubs or py.typed marker.
from laplace import Laplace
^
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```
[PEP 561]: https://peps.python.org/pep-0561/#packaging-type-information
[`import-untyped`]: https://mypy.readthedocs.io/en/stable/error_code_list.html#check-that-import-target-can-be-found-import-untyped
> Add `py.typed` to the package to enable the type annotations

- laplace/baselaplace.py
Commit 1eea27c introduces type hints in `baselaplace.py` but breaks the gradient flow through `BaseLaplace.log_likelihood(...)` since `sigma_noise` loses its gradient via [`torch.tensor(...)`]. 
This is fixed by using [`torch.as_tensor(...)`] as it converts floats but preserves the gradient. (See highlighted note [here](https://pytorch.org/docs/stable/generated/torch.tensor.html#:~:text=preserves%20autograd%20history).)
This change fixes the `UserWarning` below and passes type checking with Pylance.
```
laplace/baselaplace.py:226: UserWarning: To copy construct from a tensor, it is recommended to use
[...], rather than torch.tensor(sourceTensor).
```
[`torch.tensor(...)`]: https://pytorch.org/docs/stable/generated/torch.tensor.html
[`torch.as_tensor(...)`]: …
> Fix `sigma_noise` gradient propagation in `BaseLaplace.log_likelihood`

- laplace/subnetlaplace.py
- tests/test_subnetlaplace.py
Closes #213
This fix is based on inspecting the base class code `FullLaplace.sample()` and `DiagSubnetLaplace.sample()`. It seems to produce sensible results but a second pair of eyes is needed here. I also added a test, since the tests so far did not catch the reported issue.
> Fix ` FullSubnetLaplace.sample()`

- README.md
- pyproject.toml
- uv.lock
> Add instruction for `pip` in the README

- laplace/subnetlaplace.py
- tests/test_subnetlaplace.py
> Fix `SubnetLaplace` backend check

- laplace/baselaplace.py
- tests/test_baselaplace.py
- tests/test_functional_laplace_unit.py
- tests/test_laplace.py
- tests/test_matrix.py
- tests/test_serialization.py
- tests/test_subnetlaplace.py
- tests/test_subset_params.py
Fixes #235 
Rationale on why we don't want to throw an error:
- PyTorch works on both these 1D-output cases:
- `model(x).squeeze()` with `y.shape == model(x).shape[0:-1]`
- `model(x)` with `y.shape == model(x).shape`
- So, in the wild, users' dataloaders vary between those to `y.shape`'s. It's too much to ask to require `y.shape == model(x).shape` since PyTorch doesn't.
> Transform `y` into 2D tensor when `y.ndim == 1` and `likelihood == REGRESSION`

- .github/workflows/deploy-mkdocs.yml
- .github/workflows/pytest-asdfghjkl.yml
- .github/workflows/pytest-default.yml
- docs/calibration_gp_example.md
- examples/calibration_gp_example.py
- laplace/baselaplace.py
- laplace/utils/matrix.py
- laplace/utils/subnetmask.py
- pyproject.toml
- uv.lock
Closes #250 
Also, I modify the `deploy-mkdocs` GH actions to use `uv`. Note, `black` dep is added to format the function signatures in the docs.
How to test: `uv run --only-group docs mkdocs serve`. There should be no errors/warnings.
> Fix `mkdocs` errors; streamlining docs deploy with `uv`

- laplace/baselaplace.py
This pull request fixes a bug in the full `FullLaplace.sample` function, by changing $samples @ scale \rightarrow samples @ scale^{\top}$ which coincides with the remaining code. The bug is discussed in Issue #268.
> Fix bug in `FullLaplace.sample` (refer to Issue #268)

- docs/expectation_example.md
- examples/expectation_example.py
- laplace/baselaplace.py
- mkdocs.yml
- pyproject.toml
- uv.lock
Example of how to leverage the newly added `functional_samples` method #243. 
I also added the abstract interface for `samples` and `functional_samples` to `BaseLaplace`.
> Expectation examples
